### ISSUE TITLE
testcase runExcelcase mitm failed

### ISSUE THREAD

**Issue by fyhao** [fyhao/electron-wf#158]
Checked failed travis build https://travis-ci.org/fyhao/electron-wf/builds/345309402

```
 1) workflow_engine.js runExcelCase.wf should able to run Excel Test Case:
     Uncaught TypeError: ParserIncomingMessage is not a constructor
      at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
      at socketOnData (_http_server.js:472:20)
      at addChunk (_stream_readable.js:269:12)
      at readableAddChunk (_stream_readable.js:256:11)
      at TlsSocket.Readable.push (_stream_readable.js:213:10)
      at InternalSocket.onread (net.js:590:20)
      at InternalSocket.readData (node_modules/mitm/lib/internal_socket.js:43:13)
      at addChunk (_stream_readable.js:269:12)
      at readableAddChunk (_stream_readable.js:256:11)
      at InternalSocket.Readable.push (_stream_readable.js:213:10)
      at node_modules/mitm/lib/internal_socket.js:70:40
      at process._tickCallback (internal/process/next_tick.js:150:11)

```

It is related to this issue https://github.com/moll/node-mitm/issues/48

**Comment by fyhao** [comment]
This is outdated and no longer requires an update.

**Comment by fyhao** [comment]
Reassessed after reopening: the failure is in the obsolete `mitm`/old-Node test harness, not the Excel workflow engine. Current Excel coverage avoids that retired compatibility layer; restoring it would reintroduce an unsupported dependency.
